#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install nginx -y

# Create a new configuration file for our redirection
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Enable our new configuration file by creating a symlink to it
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test the configuration and reload nginx
sudo nginx -t
sudo systemctl reload nginx
