#!/usr/bin/env bash

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null
then
    sudo apt-get update
    sudo apt-get install nginx -y
fi

# Create a new configuration file for the redirection
sudo tee /etc/nginx/sites-available/redirect_me << EOF
server {
    listen 80;
    server_name 173937-web-01;

    location /redirect_me {
        return 301 https://www.lapololucy.tech;
    }

    # Redirect all other requests to the default Nginx welcome page
    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}
EOF

# Enable the new configuration file
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove the default Nginx configuration file
sudo rm /etc/nginx/sites-enabled/default

# Test the configuration and restart Nginx
sudo nginx -t
sudo systemctl restart nginx
