#!/bin/env bash

# Install Nginx
sudo apt update
sudo apt install nginx -y

# Add custom response header to Nginx config
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/nginx.conf > /dev/null

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo service nginx reload

